name: Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:

concurrency:
  # Cancel older, in-progress jobs from the same PR, same workflow.
  # use run_id if the job is triggered by a push to ensure
  # push-triggered jobs to not get canceled.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  functional:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/foundry-toolchain@v1
      - uses: ApeWorX/github-action@v2.4
        with:
          python-version: "3.11.4"
          ape-plugins-list: "."
      - run: ape compile --size
      - run: ape test tests/functional/ --gas --coverage

  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/foundry-toolchain@v1
      - uses: ApeWorX/github-action@v2.4
        with:
          python-version: "3.11.4"
          ape-plugins-list: "."
      - run: ape compile --size
      - run: ape test tests/integration/ -s
